// <auto-generated />
using System;
using MagazzinoLegname.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazzinoLegname.Persistence.Migrations
{
    [DbContext(typeof(MagazzinoDbContext))]
    [Migration("20260909094247_AddInboundLoadPersistence")]
    partial class AddInboundLoadPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.ApplicationSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DefaultTimberCertification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("StandardCubicMetersPerExpectedLoad23")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("StandardCubicMetersPerExpectedLoad34")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("StandardCubicMetersPerExpectedLoad44")
                        .HasColumnType("decimal(19,9)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationSettings", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.ClassificationMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperatorSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.HasIndex("MaterialGroupId");

                    b.HasIndex("OperatorId");

                    b.ToTable("ClassificationMovements", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyHistoricalRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Certification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ClassificationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExcelRow")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FinishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishedRawValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HistoricalLoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("IncomingLength")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("IncomingThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("IncomingWidth")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool?>("IsClassified")
                        .HasColumnType("bit");

                    b.Property<decimal>("LegacyAvailableCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal?>("LegacyEstimatedCubicMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LegacyQr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoadNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PackageLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("PhysicalCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("Pieces")
                        .HasColumnType("decimal(19,6)");

                    b.Property<string>("QualityNormalized")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("QualityOriginal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImportKey")
                        .IsUnique();

                    b.ToTable("LegacyHistoricalRecords", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime>("ImportedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImportedByOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImportedBySnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ImportedRows")
                        .HasColumnType("int");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<decimal>("LegacyAvailableCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<int>("LoadCount")
                        .HasColumnType("int");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PhysicalCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.HasKey("Id");

                    b.HasIndex("ImportedByOperatorId");

                    b.HasIndex("Kind", "FileFingerprint")
                        .IsUnique();

                    b.ToTable("LegacyImportBatches", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyImportKeyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExcelRow")
                        .HasColumnType("int");

                    b.Property<string>("ImportKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("ImportKey")
                        .IsUnique();

                    b.ToTable("LegacyImportKeys", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LoadEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AnnualProgressive")
                        .HasColumnType("int");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Certification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DeliveryNoteNumber")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ExpectedPackages")
                        .HasColumnType("int");

                    b.Property<Guid?>("LegacyImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacyLoadNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoadNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("LoadYear")
                        .HasColumnType("int");

                    b.Property<Guid?>("ReceiptOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceiptOperatorSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LegacyImportBatchId");

                    b.HasIndex("ReceiptOperatorId");

                    b.HasIndex("SupplierId", "LoadYear", "AnnualProgressive")
                        .IsUnique()
                        .HasFilter("[LoadYear] IS NOT NULL AND [AnnualProgressive] IS NOT NULL");

                    b.ToTable("Loads", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LoadNumberSequenceEntity", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoadYear")
                        .HasColumnType("int");

                    b.Property<int>("NextProgressive")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("SupplierId", "LoadYear");

                    b.ToTable("LoadNumberSequences", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("ConventionalThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("FinalLength")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("FinalWidth")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal?>("HistoricalValue")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("IncomingLength")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("IncomingPhysicalCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("IncomingThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("IncomingWidth")
                        .HasColumnType("decimal(12,4)");

                    b.Property<int>("InitialPieces")
                        .HasColumnType("int");

                    b.Property<bool>("IsClassified")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLegacyImport")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LegacyEstimatedCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageCount")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("UsefulThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("WasteVerified")
                        .HasColumnType("bit");

                    b.Property<decimal>("WidthAfterPlaning")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.ToTable("MaterialGroups", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.OperatorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Operators", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.PackageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AppliedPrice")
                        .HasColumnType("decimal(19,4)");

                    b.Property<DateTime>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("HistoricalPackageValue")
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("IncomingPhysicalCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<int?>("LegacyExcelRow")
                        .HasColumnType("int");

                    b.Property<Guid?>("LegacyImportBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacyPackageLabel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("LegacyQr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PackageType")
                        .HasColumnType("int");

                    b.Property<int?>("PieceCount")
                        .HasColumnType("int");

                    b.Property<string>("QrPayload")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("SupplementarySequence")
                        .HasColumnType("int");

                    b.Property<int>("TotalOfficialPackages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.HasIndex("MaterialGroupId");

                    b.HasIndex("PackageCode")
                        .IsUnique();

                    b.ToTable("Packages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Packages_SupplementaryNoValue", "[PackageType] = 0 OR ([IncomingPhysicalCubicMeters] = 0 AND [AppliedPrice] IS NULL AND [HistoricalPackageValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.PackageTerminalEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<decimal?>("InventoryCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperatorSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("ReturnOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ReturnedPhysicalCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.HasIndex("ReturnOperationId");

                    b.ToTable("PackageTerminalEvents", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Phone")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("SupplierContacts", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CertifiedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Province")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TaxCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("VatNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConventionalThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("PricePerCubicMeter")
                        .HasColumnType("decimal(19,4)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "ConventionalThickness", "ValidFrom")
                        .IsUnique();

                    b.ToTable("SupplierPrices", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierReturnOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentReference")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperatorSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.HasIndex("OperatorId");

                    b.ToTable("SupplierReturnOperations", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierThicknessConfigurationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConventionalThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<bool>("IsPlaningEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("PlaningReductionMillimeters")
                        .HasColumnType("decimal(12,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "ConventionalThickness")
                        .IsUnique();

                    b.ToTable("SupplierThicknessConfigurations", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.ThicknessFamilyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ConventionalThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("FingerJointLengthReductionMillimeters")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("MaximumIncomingThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("MinimumIncomingThickness")
                        .HasColumnType("decimal(12,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("StandardWidthReductionMillimeters")
                        .HasColumnType("decimal(12,4)");

                    b.Property<decimal>("UsefulProductionThickness")
                        .HasColumnType("decimal(12,4)");

                    b.HasKey("Id");

                    b.HasIndex("ConventionalThickness")
                        .IsUnique();

                    b.ToTable("ThicknessFamilies", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.WasteAdjustmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdjustmentBaseCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("CubicMetersAfterWholeBoardWaste")
                        .HasColumnType("decimal(19,9)");

                    b.Property<int>("DiscardedWholeBoards")
                        .HasColumnType("int");

                    b.Property<int>("GoodPieces")
                        .HasColumnType("int");

                    b.Property<int>("InitialPieces")
                        .HasColumnType("int");

                    b.Property<Guid>("LoadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaterialGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperatorSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PartialWasteCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("PartialWastePercentage")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("RealAvailableCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TheoreticalUsefulCubicMeters")
                        .HasColumnType("decimal(19,9)");

                    b.Property<decimal>("TotalClassificationWastePercentage")
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal>("WholeBoardWastePercentage")
                        .HasColumnType("decimal(9,4)");

                    b.HasKey("Id");

                    b.HasIndex("LoadId");

                    b.HasIndex("MaterialGroupId")
                        .IsUnique();

                    b.HasIndex("OperatorId");

                    b.ToTable("WasteAdjustments", (string)null);
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.ClassificationMovementEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LoadEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", "MaterialGroup")
                        .WithMany("ClassificationMovements")
                        .HasForeignKey("MaterialGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("MaterialGroup");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyHistoricalRecordEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", "Batch")
                        .WithMany("HistoricalRecords")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "ImportedByOperator")
                        .WithMany()
                        .HasForeignKey("ImportedByOperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImportedByOperator");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyImportKeyEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", "Batch")
                        .WithMany("ImportKeys")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LoadEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", "LegacyImportBatch")
                        .WithMany()
                        .HasForeignKey("LegacyImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "ReceiptOperator")
                        .WithMany()
                        .HasForeignKey("ReceiptOperatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierEntity", "Supplier")
                        .WithMany("Loads")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LegacyImportBatch");

                    b.Navigation("ReceiptOperator");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LoadNumberSequenceEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LoadEntity", "Load")
                        .WithMany("MaterialGroups")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.PackageEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LoadEntity", "Load")
                        .WithMany("Packages")
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", "MaterialGroup")
                        .WithMany("Packages")
                        .HasForeignKey("MaterialGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("MaterialGroup");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.PackageTerminalEventEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.PackageEntity", "Package")
                        .WithOne("TerminalEvent")
                        .HasForeignKey("MagazzinoLegname.Persistence.Entities.PackageTerminalEventEntity", "PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierReturnOperationEntity", "ReturnOperation")
                        .WithMany("PackageEvents")
                        .HasForeignKey("ReturnOperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operator");

                    b.Navigation("Package");

                    b.Navigation("ReturnOperation");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierContactEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierEntity", "Supplier")
                        .WithMany("Contacts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierPriceEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierEntity", "Supplier")
                        .WithMany("Prices")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierReturnOperationEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LoadEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierThicknessConfigurationEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.SupplierEntity", "Supplier")
                        .WithMany("ThicknessConfigurations")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.WasteAdjustmentEntity", b =>
                {
                    b.HasOne("MagazzinoLegname.Persistence.Entities.LoadEntity", "Load")
                        .WithMany()
                        .HasForeignKey("LoadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", "MaterialGroup")
                        .WithMany("WasteAdjustments")
                        .HasForeignKey("MaterialGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazzinoLegname.Persistence.Entities.OperatorEntity", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Load");

                    b.Navigation("MaterialGroup");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LegacyImportBatchEntity", b =>
                {
                    b.Navigation("HistoricalRecords");

                    b.Navigation("ImportKeys");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.LoadEntity", b =>
                {
                    b.Navigation("MaterialGroups");

                    b.Navigation("Packages");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.MaterialGroupEntity", b =>
                {
                    b.Navigation("ClassificationMovements");

                    b.Navigation("Packages");

                    b.Navigation("WasteAdjustments");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.PackageEntity", b =>
                {
                    b.Navigation("TerminalEvent");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierEntity", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Loads");

                    b.Navigation("Prices");

                    b.Navigation("ThicknessConfigurations");
                });

            modelBuilder.Entity("MagazzinoLegname.Persistence.Entities.SupplierReturnOperationEntity", b =>
                {
                    b.Navigation("PackageEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
